version: '3'

services:
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - hdrain-db:/data/db
    ports:
      - '27017:27017'
  server:
    container_name: server
    depends_on:
      - db
    build: '.'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - DATABASE_URL=mongodb://root:root@localhost:27017/HD_Rain?retryWrites=true&w=majority
    ports:
      - '5000:5000'
    command: 'bash -c "npm i && npm run wait-for-db && npm run dev"'

volumes:
  hdrain-db:
