-- AlterTable
ALTER TABLE "location" ALTER COLUMN "lat" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "lng" SET DATA TYPE DECIMAL(65,30);

-- AlterTable
ALTER TABLE "sensor" ALTER COLUMN "lat" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "lng" SET DATA TYPE DECIMAL(65,30);
